### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by AvinashVunnava** [AvinashVunnava/Node-Chat-App#1]
- [ ] Deploy in heroku
- [ ] Enter click send message
- [ ] Convert it into React frontend application
- [ ] Use Redis database for chat backup.
- [ ] Suppor for Emoji
- [ ] Support for group chat.
